package blooddonationmanagementsystem;

import com.sun.jdi.connect.Connector;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class registrationForm extends javax.swing.JFrame {

    Connection con;
    /**
     * Creates new form loginForm
     */
    public registrationForm() {
        initComponents();
        txt_full_name.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_pass1.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_id_number.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_pass2.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_username.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_email_address.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_pass1.setEchoChar((char) 8226);
        txt_pass2.setEchoChar((char) 8226);

        jLabel6.setText("");
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood_donation_system", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "connection failed");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_full_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_pass1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btn_sign_up = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_pass2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txt_email_address = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt_id_number = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 40, 38));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("–");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 40, 40));

        jLabel2.setBackground(new java.awt.Color(240, 240, 240));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, -1));

        jLabel3.setBackground(new java.awt.Color(240, 240, 240));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create new account...");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 490, -1));

        jLabel4.setBackground(new java.awt.Color(240, 240, 240));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("● Password");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 300, -1));

        txt_full_name.setFont(txt_full_name.getFont().deriveFont(txt_full_name.getFont().getSize()+2f));
        txt_full_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_full_name.setBorder(null);
        txt_full_name.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("_____________________________________");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 190, 40));

        jLabel7.setBackground(new java.awt.Color(240, 240, 240));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("● Full Name");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 180, -1));

        txt_pass1.setFont(txt_pass1.getFont().deriveFont(txt_pass1.getFont().getSize()+2f));
        txt_pass1.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass1.setBorder(null);
        txt_pass1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 300, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_______________________________________________________________");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 310, 40));

        btn_sign_up.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sign_up.setForeground(new java.awt.Color(102, 0, 0));
        btn_sign_up.setText("Sign Up");
        btn_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_upActionPerformed(evt);
            }
        });
        jPanel4.add(btn_sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 315, 44));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 7));

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 780, 20));

        jPanel5.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 670));

        jPanel6.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 680));

        jLabel14.setBackground(new java.awt.Color(240, 240, 240));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("● ID number");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, -1));

        jLabel15.setBackground(new java.awt.Color(240, 240, 240));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("● Confirm Password");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 300, -1));

        txt_pass2.setFont(txt_pass2.getFont().deriveFont(txt_pass2.getFont().getSize()+2f));
        txt_pass2.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass2.setBorder(null);
        txt_pass2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 300, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("_______________________________________________________________");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 310, 40));

        txt_email_address.setFont(txt_email_address.getFont().deriveFont(txt_email_address.getFont().getSize()+2f));
        txt_email_address.setForeground(new java.awt.Color(255, 255, 255));
        txt_email_address.setBorder(null);
        txt_email_address.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_email_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 300, 30));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("_______________________________________________________________");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 310, 40));

        jLabel19.setBackground(new java.awt.Color(240, 240, 240));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("● E-mail adress");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 300, -1));

        txt_username.setFont(txt_username.getFont().deriveFont(txt_username.getFont().getSize()+2f));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 300, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("_______________________________________________________________");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, 40));

        jLabel21.setBackground(new java.awt.Color(240, 240, 240));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("● Username");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Not match...");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 70, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        txt_id_number.setFont(txt_id_number.getFont().deriveFont(txt_id_number.getFont().getSize()+2f));
        txt_id_number.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_number.setBorder(null);
        txt_id_number.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_id_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 170, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("___________________________________");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 681, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(511, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_upActionPerformed

        try {
            PreparedStatement stmt_emp = con.prepareStatement("select num, id_number from employee");
            ResultSet res = stmt_emp.executeQuery();
            boolean f=false;
            while(res.next()){
                if(!txt_id_number.getText().isEmpty() && txt_id_number.getText().equals(res.getString(2))){
                     f=true;
                     break;
                }
            }
            if(f==false) JOptionPane.showMessageDialog(this, "Invalid ID number");
            else if(txt_full_name.getText().isEmpty() || txt_username.getText().isEmpty() || txt_id_number.getText().isEmpty() || txt_pass1.getText().isEmpty() || txt_pass2.getText().isEmpty()) JOptionPane.showMessageDialog(this, "missing information");
            else if(!(txt_pass1.getText().equals(txt_pass2.getText()))) JOptionPane.showMessageDialog(this, "Password don't match");
            else{
                String full_name = txt_full_name.getText(),
                username=txt_username.getText(),
                email_address=txt_email_address.getText(),
                id_number=txt_id_number.getText(),
                pass1=txt_pass1.getText(),
                pass2=txt_pass2.getText();
                
                try {
                    PreparedStatement stmt_login = con.prepareStatement("insert into login (full_name, id_number, email_address, username, pass) values (?, ?, ?, ?, ?)");
                    
                    stmt_login.setString(1, full_name);
                    stmt_login.setString(2, id_number);
                    stmt_login.setString(3, email_address);
                    stmt_login.setString(4, username);
                    stmt_login.setString(5, pass1);
                    
                    stmt_login.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, "Added to database successfully");
                    this.dispose();
                     
                } catch (SQLException ex) {
                    Logger.getLogger(donorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_sign_upActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        txt_pass1.setEchoChar((char) 0);
        txt_pass2.setEchoChar((char) 0);

    }//GEN-LAST:event_jCheckBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sign_up;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txt_email_address;
    private javax.swing.JTextField txt_full_name;
    private javax.swing.JTextField txt_id_number;
    private javax.swing.JPasswordField txt_pass1;
    private javax.swing.JPasswordField txt_pass2;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
